spring:
  thymeleaf:
    cache: false

  # 编码格式
  # 上传文件大小
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

  servlet:
    encoding:
      force: true
      enabled: true
      charset: utf-8
